### PR TITLE
Fix WebGL crash in Wallpaper Engine 1.3

### PR DESCRIPTION
**Pull request by TiEul**
The color object may not be initialized as an array, it needs to be an object as in the other places of the code.

### CODE REVIEW

**Comment by Delivator** [comment]
Didn't know about this! Can you tell me how I can reproduce this?

**Comment by Delivator** [comment]
Also with the web debugger in WE not working it's kinda annoying developing rn

**Comment by TiEul** [comment]
The debugger is fixed with Wallpaper Engine 1.3. You can rather reliably reproduce it on Wallpaper Engine 1.3 like this:

Assign a hotkey to this wallpaper.
Switch to any Scene wallpaper.
Move your mouse over your screen while pressing the hotkey combination for this wallpaper so that the mouse movement event fires immediately when the wallpaper loads.
The wallpaper will stay black or only flash up for a few frames. It might not work at first try but it will eventually work.
The problem is that the color needs to be an object rather than array. This was previously never caught due to some details how Wallpaper Engine loads web-based wallpapers. With Wallpaper Engine 1.3, the mouse movement event can be fired before mouse enter, because we have fixed the automatic focus that happened every time a web wallpaper was loaded, which triggers this previously "never reached" behavior.

**Comment by Delivator** [comment]
Interesting. Thank you for the PR!
And also thank you for fixing the debugger :)

**Pull request merged**
